image:
  empty: rancher/pause:3.1
  repository: "rancher/elemental-operator"
  tag: "1.5.0"
  imagePullPolicy: IfNotPresent

seedImage:
  repository: "rancher/seedimage-builder"
  tag: "1.5.0"
  imagePullPolicy: IfNotPresent

# default Elemental channels
defaultChannels:
  # default channels are included in the chart
  included: true
  # default channels to include
  includes:
    sle_micro_5_5: true
    sle_micro_5_5_kvm: true
    sle_micro_5_5_rt: true

# number of operator replicas to deploy
replicas: 1

# http[s] proxy server
# proxy: http://<username>@<password>:<url>:<port>

# comma separated list of domains or ip addresses that will not use the proxy
noProxy: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local

global:
  cattle:
    systemDefaultRegistry: ""

# used only if systemDefaultRegistry is empty
registryUrl: "registry.opensuse.org/isv/rancher/elemental/pr/rancher/elemental-operator/pr-800/containers"

# enable debug output for operator
debug: false

nodeSelector:
  kubernetes.io/os: linux

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 2000

tolerations:
  - key: cattle.io/os
    operator: "Equal"
    value: "linux"
    effect: NoSchedule
